CREATE DATABASE IF NOT EXISTS gama_desafio3;

USE gama_desafio3;

CREATE TABLE IF NOT EXISTS pacientes(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    nascimento DATE NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
) ENGINE = InnoDB;